import type { Metadata } from "next";
import "./globals.css";
import Head from "next/head";

export const metadata: Metadata = {
  title: "Raft Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Head>
        <link rel="icon" href="/icon.svg" />
        {/* Add other head meta tags and links as needed */}
      </Head>
      <html lang="en">
        <body>{children}</body>
      </html>
    </>
  );
}
